// EnglishCollisions.swift — SINH TỰ ĐỘNG bởi gen-english, ĐỪNG SỬA TAY.
// Từ tiếng Anh phổ biến (top-4000) mà Telex mặc định biến thành âm tiết
// Việt hợp lệ (validator không cứu được) — force-restore ở word boundary.
// Bảng là HỢP của lần sinh này với bảng đang ship (xem gen-english: monotone).
// Đã loại các từ mà tiếng Việt thắng (sẽ=sex, ơn=own… — xem gen-english).
// Regenerate:  swift run gen-english google-10000-english.txt 4000 //              Sources/TelexCore/EnglishCollisions.swift
enum EnglishCollisions {
    /// Sorted ascii, lowercase. ~498 từ, tra Set ở boundary (không trên hot path).
    static let words: Set<String> = [        "access", "accessible", "accessories", "accessory", "across", "address", "addresses", "advantage",
        "affairs", "affect", "affected", "affiliate", "affiliates", "affordable", "agricultural", "agriculture",
        "aircraft", "airport", "alabama", "analysis", "appropriate", "architecture", "arizona", "arkansas",
        "arm", "arms", "arrangements", "array", "artists", "arts", "ask", "aspects",
        "ass", "assembly", "assessment", "asset", "assets", "assigned", "assist", "assistance",
        "assistant", "associate", "associated", "associates", "association", "assume", "atlanta", "authorized",
        "avatar", "awareness", "barbara", "bars", "basis", "bass", "best", "between",
        "bias", "bits", "bless", "boats", "border", "born", "boss", "boxes",
        "brass", "breasts", "buffalo", "business", "businesses", "busy", "buys", "canada",
        "career", "careers", "carried", "carrier", "carry", "cars", "cases", "cast",
        "causes", "census", "character", "characters", "charms", "charter", "charts", "chess",
        "chosen", "christmas", "class", "classes", "classic", "classical", "classified", "classifieds",
        "classroom", "cliff", "coast", "coffee", "commission", "congress", "consistent", "constitutes",
        "consultants", "contemporary", "contractor", "contractors", "controller", "converter", "core", "corner",
        "corporate", "corporation", "correct", "cost", "costs", "courses", "crisis", "cross",
        "cruises", "currency", "current", "currently", "curriculum", "database", "databases", "december",
        "decided", "decisions", "dedicated", "delete", "designs", "diff", "difference", "differences",
        "different", "difficult", "dimensions", "director", "directories", "directors", "directory", "discounts",
        "discuss", "discussed", "discussion", "discussions", "disease", "diseases", "disorders", "displays",
        "does", "doom", "door", "doors", "dose", "down", "dress", "dvd",
        "dvds", "earlier", "effect", "effective", "effectively", "effects", "efficiency", "efficient",
        "effort", "efforts", "element", "elementary", "elements", "enterprise", "enterprises", "ericsson",
        "err", "error", "errors", "essential", "establish", "established", "estimates", "exists",
        "expenses", "explorer", "express", "expressed", "expression", "february", "fitness", "former",
        "forward", "furniture", "further", "fuss", "gary", "gene", "genre", "gets",
        "ghost", "gifts", "glass", "glossary", "goes", "gore", "governor", "grass",
        "greece", "gross", "guess", "guests", "guns", "guys", "hardcore", "hardcover",
        "hardware", "harry", "her", "here", "hiss", "horse", "hose", "hospitals",
        "host", "houses", "implemented", "increases", "independent", "institutions", "interests", "interior",
        "interracial", "investments", "islands", "issue", "issued", "issues", "jeff", "jesus",
        "jewellery", "kansas", "kiss", "kits", "laboratory", "larger", "last", "law",
        "laws", "lesbians", "less", "lesson", "lessons", "libraries", "library", "list",
        "listings", "lists", "literature", "loans", "lose", "loss", "major", "manufacturer",
        "maps", "marks", "marriage", "married", "mary", "mask", "mass", "massage",
        "massive", "meets", "mens", "mess", "message", "messages", "messenger", "mirror",
        "miss", "missed", "missing", "mission", "mississippi", "missouri", "moderator", "more",
        "moss", "most", "must", "narrow", "nasa", "necessary", "needed", "northern",
        "nose", "occurred", "off", "offer", "offered", "offering", "offers", "office",
        "officer", "officers", "offices", "official", "officials", "offline", "operator", "operators",
        "or", "order", "ordered", "ordering", "orders", "organization", "organized", "outdoor",
        "outdoors", "outlook", "pair", "pairs", "para", "paragraph", "parameter", "parameters",
        "paris", "parks", "particular", "particularly", "partner", "partners", "partnership", "parts",
        "pass", "passed", "password", "past", "pays", "peer", "peers", "pens",
        "per", "permission", "personals", "persons", "pets", "photos", "physics", "pieces",
        "pins", "piss", "poems", "poor", "porn", "porno", "ports", "pose",
        "positions", "possible", "possibly", "post", "posts", "preferences", "preferred", "presents",
        "press", "pressure", "process", "processes", "processing", "processor", "professional", "professor",
        "progress", "proposals", "protocol", "provisions", "purposes", "pussy", "puts", "quarter",
        "questions", "raw", "reasons", "refer", "reference", "references", "referred", "releases",
        "remember", "represents", "requests", "researchers", "residents", "resistance", "response", "responses",
        "responsible", "rest", "results", "risks", "rooms", "rose", "russia", "russian",
        "sass", "saw", "says", "secretary", "see", "seem", "seemed", "seems",
        "sees", "selected", "sense", "september", "server", "servers", "session", "sessions",
        "settlement", "sexo", "soon", "sorry", "staff", "stainless", "statistics", "stress",
        "stuff", "submission", "success", "successful", "successfully", "sufficient", "suggestions", "superior",
        "surgery", "swiss", "systems", "tariff", "task", "tasks", "teens", "temperature",
        "temporary", "tennessee", "term", "terms", "territory", "test", "tests", "themes",
        "themselves", "there", "these", "thongs", "those", "thousands", "tomorrow", "tons",
        "town", "traffic", "transactions", "transmission", "trees", "trips", "troops", "trust",
        "turn", "turns", "universities", "unless", "unsubscribe", "usa", "uses", "vary",
        "versions", "verzeichnis", "virus", "visa", "visits", "war", "warranty", "wars",
        "wax", "websites", "wireless", "wisconsin", "workers", "writer", "writers", "wrong",
        "zero", "zoom",
    ]
}